=head1 NAME

pwgrep - Managing passwords...

=head1 Synopsis

  fwipe <FILE>            - Wiping a file
  pwdbls                  - Listing available DBs
  pwedit [OPTS]           - Editing current DB
  pwfadd <FILE>           - Adding a file to FDB
  pwfcat <NAME>           - Printing a file from filestore to stdout
  pwfdel <NAME>           - Deleting a file from filestore
  pwgrep [OPTS] <REGEX>   - Grepping current DB
  pwldb                   - Synonym of pwdbls
  pwupdate                - Updating FDB and all DBs
  pwhelp                  - Printing this help screen

Where OPTS are:
  -o                      - Offline mode
  -d <DB NAME>            - Using a specific DB
  -a                 - Searching all available DBs or categories at once

=head1 Tutorial

Please go to L<http://pwgrep.buetow.org>.
